# -*- coding: utf-8 -*-
from __future__ import print_function
import datetime as dt
import logging

from . import Property, PropertyDefinition, BaseType, dateTimeBase

__all__ = ['dateTime', ]

class dateTime(dateTimeBase):
    """Autogenerated dateTime type."""
    _regex = '-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?'    
    
    value = Property(PropertyDefinition('value', str, '1', '1', 'xmlAttr'))


