# -*- coding: utf-8 -*-
from __future__ import print_function
import datetime as dt
import logging

from . import Property, PropertyDefinition
from . import FHIRBase, Element, Extension

from .backboneelement import BackboneElement
from .domainresource import DomainResource

from ._string import string
from ._time import time
from ._code import code
from ._datetime import dateTime
from ._instant import instant

from .sampleddata import SampledData
from .period import Period
from .codeableconcept import CodeableConcept
from .range import Range
from .reference import Reference
from .backboneelement import BackboneElement
from .attachment import Attachment
from .ratio import Ratio
from .quantity import Quantity
from .identifier import Identifier

__author__ = "Melle Sieswerda"
__copyright__  = "Copyright 2017, Melle Sieswerda"
__license__ = "GPL"
__version__ = "0.8"

__all__ = ['Observation']


class ReferenceRange(BackboneElement):
    """Autogenerated class for implicit type."""
    low = Property(PropertyDefinition('low', 'Quantity', '0', '1'))    
    high = Property(PropertyDefinition('high', 'Quantity', '0', '1'))    
    meaning = Property(PropertyDefinition('meaning', 'CodeableConcept', '0', '1'))    
    age = Property(PropertyDefinition('age', 'Range', '0', '1'))    
    text = Property(PropertyDefinition('text', 'string', '0', '1'))    

class Related(BackboneElement):
    """Autogenerated class for implicit type."""
    type = Property(PropertyDefinition('type', 'code', '0', '1'))    
    target = Property(PropertyDefinition('target', ['Reference(reference="http://hl7.org/fhir/StructureDefinition/Observation")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse")'], '1', '1'))    

class Component(BackboneElement):
    """Autogenerated class for implicit type."""
    code = Property(PropertyDefinition('code', 'CodeableConcept', '1', '1'))    
    value = Property(PropertyDefinition('value', ['Quantity', 'CodeableConcept', 'string', 'Range', 'Ratio', 'SampledData', 'Attachment', 'time', 'dateTime', 'Period'], '0', '1'))    
    dataAbsentReason = Property(PropertyDefinition('dataAbsentReason', 'CodeableConcept', '0', '1'))    
    referenceRange = Property(PropertyDefinition('referenceRange', 'ReferenceRange', '0', '*'))    

# ------------------------------------------------------------------------------
# Observation
# ------------------------------------------------------------------------------
class Observation(DomainResource):
    """
    Measurements and simple assertions made about a patient, device or
    other subject.
    
    Autogenerated class.
    """
    _url = 'http://hl7.org/fhir/StructureDefinition/Observation'
    
    identifier = Property(PropertyDefinition('identifier', Identifier, '0', '*'))
    status = Property(PropertyDefinition('status', code, '1', '1'))
    category = Property(PropertyDefinition('category', CodeableConcept, '0', '1'))
    code = Property(PropertyDefinition('code', CodeableConcept, '1', '1'))
    subject = Property(PropertyDefinition('subject', ['Reference(reference="http://hl7.org/fhir/StructureDefinition/Patient")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/Group")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/Device")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/Location")'], '0', '1'))
    encounter = Property(PropertyDefinition('encounter', Reference(reference="http://hl7.org/fhir/StructureDefinition/Encounter"), '0', '1'))
    effective = Property(PropertyDefinition('effective', ['dateTime', 'Period'], '0', '1'))
    issued = Property(PropertyDefinition('issued', instant, '0', '1'))
    performer = Property(PropertyDefinition('performer', ['Reference(reference="http://hl7.org/fhir/StructureDefinition/Practitioner")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/Organization")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/Patient")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/RelatedPerson")'], '0', '*'))
    value = Property(PropertyDefinition('value', ['Quantity', 'CodeableConcept', 'string', 'Range', 'Ratio', 'SampledData', 'Attachment', 'time', 'dateTime', 'Period'], '0', '1'))
    dataAbsentReason = Property(PropertyDefinition('dataAbsentReason', CodeableConcept, '0', '1'))
    interpretation = Property(PropertyDefinition('interpretation', CodeableConcept, '0', '1'))
    comments = Property(PropertyDefinition('comments', string, '0', '1'))
    bodySite = Property(PropertyDefinition('bodySite', CodeableConcept, '0', '1'))
    method = Property(PropertyDefinition('method', CodeableConcept, '0', '1'))
    specimen = Property(PropertyDefinition('specimen', Reference(reference="http://hl7.org/fhir/StructureDefinition/Specimen"), '0', '1'))
    device = Property(PropertyDefinition('device', ['Reference(reference="http://hl7.org/fhir/StructureDefinition/Device")', 'Reference(reference="http://hl7.org/fhir/StructureDefinition/DeviceMetric")'], '0', '1'))
    referenceRange = Property(PropertyDefinition('referenceRange', ReferenceRange, '0', '*'))
    related = Property(PropertyDefinition('related', Related, '0', '*'))
    component = Property(PropertyDefinition('component', Component, '0', '*'))
    