# -*- coding: utf-8 -*-
from __future__ import print_function
import datetime as dt
import logging

from . import Property, PropertyDefinition
from . import FHIRBase, Element, Extension, Reference

from .backboneelement import BackboneElement
from .domainresource import DomainResource

from ._boolean import boolean
from ._code import code
from ._datetime import dateTime
from ._instant import instant
from ._string import string
from ._time import time

from .attachment import Attachment
from .backboneelement import BackboneElement
from .codeableconcept import CodeableConcept
from .identifier import Identifier
from .period import Period
from .quantity import Quantity
from .range import Range
from .ratio import Ratio
from .sampleddata import SampledData

__author__ = "Melle Sieswerda"
__copyright__  = "Copyright 2017, Melle Sieswerda"
__license__ = "GPL"
__version__ = "0.8"

__all__ = ['Observation']

class ReferenceRange(BackboneElement):
    """Autogenerated class for implicit type."""
    low = Property(PropertyDefinition('low', 'Quantity', '0', '1'))    
    high = Property(PropertyDefinition('high', 'Quantity', '0', '1'))    
    type = Property(PropertyDefinition('type', 'CodeableConcept', '0', '1'))    
    appliesTo = Property(PropertyDefinition('appliesTo', 'CodeableConcept', '0', '*'))    
    age = Property(PropertyDefinition('age', 'Range', '0', '1'))    
    text = Property(PropertyDefinition('text', 'string', '0', '1'))    

class Related(BackboneElement):
    """Autogenerated class for implicit type."""
    type = Property(PropertyDefinition('type', 'code', '0', '1'))    
    target = Property(PropertyDefinition('target', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '1', '1'))    

class Component(BackboneElement):
    """Autogenerated class for implicit type."""
    code = Property(PropertyDefinition('code', 'CodeableConcept', '1', '1'))    
    value = Property(PropertyDefinition('value', ['Quantity', 'CodeableConcept', 'string', 'Range', 'Ratio', 'SampledData', 'Attachment', 'time', 'dateTime', 'Period'], '0', '1'))    
    dataAbsentReason = Property(PropertyDefinition('dataAbsentReason', 'CodeableConcept', '0', '1'))    
    interpretation = Property(PropertyDefinition('interpretation', 'CodeableConcept', '0', '1'))    
    referenceRange = Property(PropertyDefinition('referenceRange', 'ReferenceRange', '0', '*'))    


# ------------------------------------------------------------------------------
# Observation
# ------------------------------------------------------------------------------
class Observation(DomainResource):
    """
    Measurements and simple assertions made about a patient, device or
    other subject.
    
    Autogenerated class.
    """
    _url = 'http://hl7.org/fhir/StructureDefinition/Observation'
    
    identifier = Property(PropertyDefinition('identifier', Identifier, '0', '*'))
    basedOn = Property(PropertyDefinition('basedOn', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '*'))
    status = Property(PropertyDefinition('status', code, '1', '1'))
    category = Property(PropertyDefinition('category', CodeableConcept, '0', '*'))
    code = Property(PropertyDefinition('code', CodeableConcept, '1', '1'))
    subject = Property(PropertyDefinition('subject', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    context = Property(PropertyDefinition('context', ['Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    effective = Property(PropertyDefinition('effective', ['dateTime', 'Period'], '0', '1'))
    issued = Property(PropertyDefinition('issued', instant, '0', '1'))
    performer = Property(PropertyDefinition('performer', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '*'))
    value = Property(PropertyDefinition('value', ['Quantity', 'CodeableConcept', 'string', 'boolean', 'Range', 'Ratio', 'SampledData', 'Attachment', 'time', 'dateTime', 'Period'], '0', '1'))
    dataAbsentReason = Property(PropertyDefinition('dataAbsentReason', CodeableConcept, '0', '1'))
    interpretation = Property(PropertyDefinition('interpretation', CodeableConcept, '0', '1'))
    comment = Property(PropertyDefinition('comment', string, '0', '1'))
    bodySite = Property(PropertyDefinition('bodySite', CodeableConcept, '0', '1'))
    method = Property(PropertyDefinition('method', CodeableConcept, '0', '1'))
    specimen = Property(PropertyDefinition('specimen', Reference(reference="None"), '0', '1'))
    device = Property(PropertyDefinition('device', ['Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    referenceRange = Property(PropertyDefinition('referenceRange', ReferenceRange, '0', '*'))
    related = Property(PropertyDefinition('related', Related, '0', '*'))
    component = Property(PropertyDefinition('component', Component, '0', '*'))
