# -*- coding: utf-8 -*-
from __future__ import print_function
import datetime as dt
import logging

from . import Property, PropertyDefinition
from . import FHIRBase, Element, Extension, Reference

from .backboneelement import BackboneElement
from .domainresource import DomainResource

from ._boolean import boolean
from ._code import code
from ._date import date
from ._datetime import dateTime
from ._decimal import decimal
from ._integer import integer
from ._string import string
from ._time import time
from ._uri import uri

from .attachment import Attachment
from .backboneelement import BackboneElement
from .coding import Coding
from .identifier import Identifier
from .quantity import Quantity

__author__ = "Melle Sieswerda"
__copyright__  = "Copyright 2017, Melle Sieswerda"
__license__ = "GPL"
__version__ = "0.8"

__all__ = ['QuestionnaireResponse']

class Item(BackboneElement):
    """Autogenerated class for implicit type."""
    linkId = Property(PropertyDefinition('linkId', 'string', '1', '1'))    
    definition = Property(PropertyDefinition('definition', 'uri', '0', '1'))    
    text = Property(PropertyDefinition('text', 'string', '0', '1'))    
    subject = Property(PropertyDefinition('subject', 'Reference(reference="None")', '0', '1'))    
    answer = Property(PropertyDefinition('answer', 'Answer', '0', '*'))    
    item = Property(PropertyDefinition('item', 'Item', '0', '*'))    

class Answer(BackboneElement):
    """Autogenerated class for implicit type."""
    value = Property(PropertyDefinition('value', ['boolean', 'decimal', 'integer', 'date', 'dateTime', 'time', 'string', 'uri', 'Attachment', 'Coding', 'Quantity', 'Reference(reference="None")'], '0', '1'))    
    item = Property(PropertyDefinition('item', 'Item', '0', '*'))    


# ------------------------------------------------------------------------------
# QuestionnaireResponse
# ------------------------------------------------------------------------------
class QuestionnaireResponse(DomainResource):
    """
    A structured set of questions and their answers. The questions are
    ordered and grouped into coherent subsets, corresponding to the
    structure of the grouping of the questionnaire being responded to.
    
    Autogenerated class.
    """
    _url = 'http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse'
    
    identifier = Property(PropertyDefinition('identifier', Identifier, '0', '1'))
    basedOn = Property(PropertyDefinition('basedOn', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '*'))
    parent = Property(PropertyDefinition('parent', ['Reference(reference="None")', 'Reference(reference="None")'], '0', '*'))
    questionnaire = Property(PropertyDefinition('questionnaire', Reference(reference="None"), '0', '1'))
    status = Property(PropertyDefinition('status', code, '1', '1'))
    subject = Property(PropertyDefinition('subject', Reference(reference="None"), '0', '1'))
    context = Property(PropertyDefinition('context', ['Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    authored = Property(PropertyDefinition('authored', dateTime, '0', '1'))
    author = Property(PropertyDefinition('author', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    source = Property(PropertyDefinition('source', ['Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    item = Property(PropertyDefinition('item', Item, '0', '*'))
