# -*- coding: utf-8 -*-
from __future__ import print_function
import datetime as dt
import logging

from . import Property, PropertyDefinition
from . import FHIRBase, Element, Extension


from ._uri import uri
from ._id import id
from ._code import code

from .meta import Meta

__author__ = "Melle Sieswerda"
__copyright__  = "Copyright 2017, Melle Sieswerda"
__license__ = "GPL"
__version__ = "0.8"

__all__ = ['Resource']


# ------------------------------------------------------------------------------
# Resource
# ------------------------------------------------------------------------------
class Resource(FHIRBase):
    """
    This is the base resource type for everything.
    
    Autogenerated class.
    """
    _url = 'http://hl7.org/fhir/StructureDefinition/Resource'
    
    id = Property(PropertyDefinition('id', id, '0', '1'))
    meta = Property(PropertyDefinition('meta', Meta, '0', '1'))
    implicitRules = Property(PropertyDefinition('implicitRules', uri, '0', '1'))
    language = Property(PropertyDefinition('language', code, '0', '1'))
    