# -*- coding: utf-8 -*-
from __future__ import print_function
import datetime as dt
import logging

from . import Property, PropertyDefinition
from . import FHIRBase, Element, Extension, Reference


from ._base64binary import base64Binary
from ._code import code
from ._uri import uri
from ._instant import instant

from .coding import Coding

__author__ = "Melle Sieswerda"
__copyright__  = "Copyright 2017, Melle Sieswerda"
__license__ = "GPL"
__version__ = "0.8"

__all__ = ['Signature']


# ------------------------------------------------------------------------------
# Signature
# ------------------------------------------------------------------------------
class Signature(Element):
    """
    A digital signature along with supporting context. The signature may
    be electronic/cryptographic in nature, or a graphical image
    representing a hand-written signature, or a signature process.
    Different signature approaches have different utilities.
    
    Autogenerated class.
    """
    _url = 'http://hl7.org/fhir/StructureDefinition/Signature'
    
    type = Property(PropertyDefinition('type', Coding, '1', '*'))
    when = Property(PropertyDefinition('when', instant, '1', '1'))
    who = Property(PropertyDefinition('who', ['uri', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '1', '1'))
    onBehalfOf = Property(PropertyDefinition('onBehalfOf', ['uri', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")', 'Reference(reference="None")'], '0', '1'))
    contentType = Property(PropertyDefinition('contentType', code, '0', '1'))
    blob = Property(PropertyDefinition('blob', base64Binary, '0', '1'))
